### ISSUE TITLE
Compatibility with Eilistraee's Song

### ISSUE THREAD

**Issue by Grammarsalad** [UnearthedArcana/Faiths_and_Powers#141]
When Eilistraee's Song (current version, 6.6) is already installed, then trying to install FnP's sphere system fails with the following error:
ERROR: internal label [B_dom01_41] appears 2 times in processed DLG [B_D_DWA]
ERROR: postprocessing [B_D_DWA]: Failure("cannot resolve label")
Stopping installation because of error

**Comment by Grammarsalad** [comment]
User was using an old version. Not an issue

**Comment by ahungry** [comment]
I'm getting a similar issue - I don't know what mod is causing it, I've only installed some new quest/npc/item mods, but received this error:

ERROR: internal label [B_dom01_79] appears 2 times in processed DLG [B_D_DWA]
ERROR: postprocessing [B_D_DWA]: Failure("cannot resolve label")

Trying to grep the directory/file names to see what would have included...
