### ISSUE TITLE
Release 0.71 bug

### ISSUE THREAD

**Issue by ALIENQuake** [UnearthedArcana/Faiths_and_Powers#84]
Extracted clean copy of BG2EE, using 1], facing this error:

> Compiling 1 dialogue file ...
> 
> [action list near line 346, column 62 of faiths_and_powers/deity/b_d_d.d] PARSE WARNING at line 346 column 1-13
> Near Text: )
>         [AddKit] argument [TALOS] not found in [KIT.IDS]
> 
> [action list near line 361, column 60 of faiths_and_powers/deity/b_d_d.d] PARSE WARNING at line 361 column 1-12
> Near Text: )
>         [AddKit] argument [HELM] not found in [KIT.IDS]
> 
> [action list near line 1123, column 68 of faiths_and_powers/deity/b_d_d.d] PARSE WARNING at line 1123 column 1-21
> Near Text: )
>         [AddKit] argument [TOTEMIC_DRUID] not found in [KIT.IDS]
> 
> [action list near line 1158, column 61 of faiths_and_powers/deity/b_d_d.d] PARSE WARNING at line 1158 column 1-20
> Near Text: )
>         [AddKit] argument [BEAST_FRIEND] not found in [KIT.IDS]
> 
> [action list near line 1878, column 68 of faiths_and_powers/deity/b_d_d.d] PARSE WARNING at line 1878 column 1-21
> Near Text: )
>         [AddKit] argument [UNDEAD_HUNTER] not found in [KIT.IDS]
> 
> [action list near line 1891, column 68 of faiths_and_powers/deity/b_d_d.d] PARSE WARNING at line 1891 column 1-21
> Near Text: )
>         [AddKit] argument [UNDEAD_HUNTER] not found in [KIT.IDS]
> ERROR: internal label [B_dom017_6] appears 2 times in processed DLG [B_D_DWA]
> ERROR: postprocessing [B_D_DWA]: Failure("cannot resolve label")
> Stopping installation because of error.
> Stopping installation because of error.
> Stopping installation because of error.
> 
> ERROR Installing [Select an installation method below: -> ALL the new kits, the kit selection dialogue, and the sphere system], rolling back to previous state
> Will uninstall 1645 files for [FAITHS_AND_POWERS/FAITHS_AND_POWERS.TP2] component 101.
> Uninstalled    1645 files for [FAITHS_AND_POWERS/FAITHS_AND_POWERS.TP2] component 101.
> ERROR: Failure("cannot resolve label")
> PLEASE email the file SETUP-FAITHS_AND_POWERS.DEBUG to SubtleD and Grammarsalad
> Using Language [English]
> 
> Install Component [Select an installation method below:]?
> [N]o, [Q]uit or choose one:
>  1] ALL the new kits, the kit selection dialogue, and the sphere system

**Comment by Grammarsalad** [comment]
Hopefully fixed in 0.71a
